"""Add planning tables

Revision ID: 0d9ac0bebfda
Revises: c2042d9ae5c6
Create Date: 2025-09-17 14:54:58.835525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9ac0bebfda'
down_revision = 'c2042d9ae5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initial_idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creative_expansion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('initial_idea_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('theme', sa.String(length=200), nullable=True),
    sa.Column('innovation_points', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initial_idea_id'], ['initial_idea.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basic_concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('creative_expansion_id', sa.Integer(), nullable=False),
    sa.Column('world_setting', sa.Text(), nullable=True),
    sa.Column('plot_development', sa.Text(), nullable=True),
    sa.Column('character_design', sa.Text(), nullable=True),
    sa.Column('structure_design', sa.Text(), nullable=True),
    sa.Column('style_design', sa.Text(), nullable=True),
    sa.Column('theme_expression', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creative_expansion_id'], ['creative_expansion.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basic_concept')
    op.drop_table('creative_expansion')
    op.drop_table('initial_idea')
    # ### end Alembic commands ###
