"""Update project relationships

Revision ID: ca0d5894e827
Revises: 0d9ac0bebfda
Create Date: 2025-09-17 15:00:45.011312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0d5894e827'
down_revision = '0d9ac0bebfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspiration')
    op.drop_table('creative_idea')
    op.drop_table('inspiration_material')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspiration_material',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inspiration_id', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['inspiration_id'], ['inspiration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creative_idea',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('inspiration_id', sa.INTEGER(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('genre', sa.VARCHAR(length=50), nullable=True),
    sa.Column('theme', sa.VARCHAR(length=200), nullable=True),
    sa.Column('innovation_points', sa.TEXT(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['inspiration_id'], ['inspiration.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspiration',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
