"""Add full concept fields

Revision ID: f118f9a04bb1
Revises: ca0d5894e827
Create Date: 2025-09-18 11:32:55.371653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f118f9a04bb1'
down_revision = 'ca0d5894e827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_concept', schema=None) as batch_op:
        batch_op.add_column(sa.Column('culture_background', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('special_elements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('core_conflict', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plot_outline', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('subplot_design', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('key_events', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('plot_progression', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('main_characters', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('supporting_characters', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('character_relationships', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('character_arcs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('theme_design', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('philosophical_elements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('social_commentary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('symbolic_system', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('narrative_perspective', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('timeline_structure', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pacing_design', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('foreshadowing', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('writing_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('language_features', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('atmosphere_building', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('literary_devices', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chapter_structure', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('volume_planning', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('word_count_target', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estimated_chapters', sa.Integer(), nullable=True))
        batch_op.drop_column('theme_expression')
        batch_op.drop_column('character_design')
        batch_op.drop_column('structure_design')
        batch_op.drop_column('plot_development')
        batch_op.drop_column('style_design')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_concept', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_design', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('plot_development', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('structure_design', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('character_design', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('theme_expression', sa.TEXT(), nullable=True))
        batch_op.drop_column('estimated_chapters')
        batch_op.drop_column('word_count_target')
        batch_op.drop_column('volume_planning')
        batch_op.drop_column('chapter_structure')
        batch_op.drop_column('literary_devices')
        batch_op.drop_column('atmosphere_building')
        batch_op.drop_column('language_features')
        batch_op.drop_column('writing_style')
        batch_op.drop_column('foreshadowing')
        batch_op.drop_column('pacing_design')
        batch_op.drop_column('timeline_structure')
        batch_op.drop_column('narrative_perspective')
        batch_op.drop_column('symbolic_system')
        batch_op.drop_column('social_commentary')
        batch_op.drop_column('philosophical_elements')
        batch_op.drop_column('theme_design')
        batch_op.drop_column('character_arcs')
        batch_op.drop_column('character_relationships')
        batch_op.drop_column('supporting_characters')
        batch_op.drop_column('main_characters')
        batch_op.drop_column('plot_progression')
        batch_op.drop_column('key_events')
        batch_op.drop_column('subplot_design')
        batch_op.drop_column('plot_outline')
        batch_op.drop_column('core_conflict')
        batch_op.drop_column('special_elements')
        batch_op.drop_column('culture_background')

    # ### end Alembic commands ###
